"use client";
import { movementTypeLabels,resolveMovement,useStockDemo,type AdjustmentDirection,type MovementType } from "@software-factory/stock-core";
import { useState,type FormEvent } from "react";import { PageIntro,Panel } from "../_components/pulse-ui";
const tone:Record<MovementType,string>={inbound:"bg-emerald-50 text-emerald-700",outbound:"bg-blue-50 text-blue-700",adjustment:"bg-amber-50 text-amber-700",transfer:"bg-violet-50 text-violet-700"};
const messages={"movement-applied":"Movimiento aplicado","transfer-complete":"Transferencia completada","invalid-quantity":"Ingresá una cantidad válida","invalid-product":"Seleccioná un producto","location-required":"Seleccioná las ubicaciones necesarias","same-location":"Origen y destino deben ser diferentes","insufficient-stock":"Stock insuficiente","reset-complete":"Escenario restablecido"}as const;
export function MovementsExperience(){
 const demo=useStockDemo();const[open,setOpen]=useState(false);const[type,setType]=useState<MovementType>("inbound");const[productId,setProduct]=useState(demo.products[0]?.id??"");const[quantity,setQuantity]=useState("1");const[source,setSource]=useState("");const[destination,setDestination]=useState("");const[direction,setDirection]=useState<AdjustmentDirection>("increase");
 const submit=(event:FormEvent)=>{event.preventDefault();const result=demo.applyMovement({productId,type,quantity:Number(quantity),adjustmentDirection:type==="adjustment"?direction:undefined,sourceLocationId:type==="outbound"||type==="transfer"||(type==="adjustment"&&direction==="decrease")?source:undefined,destinationLocationId:type==="inbound"||type==="transfer"||(type==="adjustment"&&direction==="increase")?destination:undefined,actorName:"Marcos Vega",reference:"Movimiento demo"});if(result.ok)setOpen(false)};
 return <><PageIntro eyebrow="Trazabilidad visual" title="Movimientos" description="Entradas, salidas, ajustes y transferencias del escenario operativo." action={<div className="flex gap-2"><button className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-xs font-bold" onClick={demo.reset}>Reset demo</button><button className="rounded-xl bg-[#15242d] px-5 py-3 text-sm font-bold text-white" onClick={()=>setOpen(true)}>+ Registrar movimiento</button></div>}/>
 {demo.feedback?<p className="mb-4 rounded-xl bg-teal-50 px-4 py-3 text-sm font-bold text-teal-800">{messages[demo.feedback]}</p>:null}
 <div className="mb-4 flex gap-2 overflow-x-auto">{([['all','Todos'],['inbound','Entradas'],['outbound','Salidas'],['adjustment','Ajustes'],['transfer','Transferencias']]as const).map(([id,label])=><button className={`whitespace-nowrap rounded-xl px-4 py-2 text-xs font-bold ${demo.state.filters.movementType===id?'bg-[#15242d] text-white':'border border-slate-200 bg-white text-slate-500'}`} key={id} onClick={()=>demo.setMovementFilter(id)}>{label}</button>)}</div>
 <Panel className="overflow-hidden"><div className="divide-y divide-slate-100">{demo.filteredMovements.map(m=>{const r=resolveMovement(m,demo.products,demo.state.locations);const sign=m.type==='inbound'||m.adjustmentDirection==='increase'?'+':m.type==='transfer'?'':'−';return <div className="grid gap-3 p-5 md:grid-cols-[.8fr_1.8fr_.7fr_1.4fr_1fr] md:items-center" key={m.id}><span className={`w-fit rounded-full px-3 py-1 text-[10px] font-bold uppercase ${tone[m.type]}`}>{movementTypeLabels[m.type]}</span><div><p className="font-semibold">{r.product?.name}</p><p className="text-xs text-slate-400">{r.product?.sku}</p></div><b className="text-xl">{sign}{m.quantity}</b><p className="text-xs text-slate-500">{r.sourceLocation?.name??'Recepción'} → {r.destinationLocation?.name??'Salida'}</p><div><p className="text-xs font-semibold">08 sep · {m.occurredAt.slice(11,16)}</p><p className="mt-1 text-[10px] text-slate-400">{m.actorName} · {m.reference}</p></div></div>})}</div></Panel>
 {open?<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4"><Panel className="w-full max-w-lg p-6"><form onSubmit={submit}><h3 className="text-xl font-bold">Registrar movimiento</h3><p className="mt-2 text-sm text-slate-500">Actualiza únicamente el escenario local de demostración.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><select className="rounded-xl border p-3" value={type} onChange={e=>setType(e.target.value as MovementType)}><option value="inbound">Entrada</option><option value="outbound">Salida</option><option value="adjustment">Ajuste</option><option value="transfer">Transferencia</option></select><select className="rounded-xl border p-3" value={productId} onChange={e=>setProduct(e.target.value)}>{demo.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><input className="rounded-xl border p-3" min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/>{type==='adjustment'?<select className="rounded-xl border p-3" value={direction} onChange={e=>setDirection(e.target.value as AdjustmentDirection)}><option value="increase">Ajuste positivo</option><option value="decrease">Ajuste negativo</option></select>:null}{type==='outbound'||type==='transfer'||(type==='adjustment'&&direction==='decrease')?<select className="rounded-xl border p-3" value={source} onChange={e=>setSource(e.target.value)}><option value="">Origen</option>{demo.state.locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select>:null}{type==='inbound'||type==='transfer'||(type==='adjustment'&&direction==='increase')?<select className="rounded-xl border p-3" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Destino</option>{demo.state.locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select>:null}</div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="rounded-lg bg-[#15242d] px-4 py-2 font-bold text-white">Registrar</button></div></form></Panel></div>:null}</>;
}
