import type{ReactNode}from"react";
export const usd=(n:number)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
export const shortDate=(s:string)=>new Intl.DateTimeFormat("es-AR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(s));
export function Intro({eyebrow,title,description,action}:{readonly eyebrow:string;readonly title:string;readonly description:string;readonly action?:ReactNode}){return <div className="mb-8 flex flex-col justify-between gap-5 border-b border-stone-200/70 pb-7 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-[#96703a]">{eyebrow}</p><h2 className="mt-2 font-serif text-4xl font-semibold tracking-[-.025em] text-[#142b40] sm:text-[46px] sm:leading-none">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-500">{description}</p></div>{action}</div>}
export function Panel({children,className=""}:{readonly children:ReactNode;readonly className?:string}){return <section className={`nova-surface min-w-0 ${className}`}>{children}</section>}
export function Pill({children,tone="navy"}:{readonly children:ReactNode;readonly tone?:"navy"|"sand"|"green"}){return <span className={`inline-flex rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide ${tone==="green"?"bg-emerald-50 text-emerald-700":tone==="sand"?"bg-[#eee5d6] text-[#785e38]":"bg-[#e5ebf0] text-[#27465f]"}`}>{children}</span>}
export function Drawer({title,onClose,children}:{readonly title:string;readonly onClose:()=>void;readonly children:ReactNode}){return <div className="fixed inset-0 z-50 flex justify-end bg-[#0e1c28]/45 backdrop-blur-[2px]" onMouseDown={onClose}><aside className="h-full w-full max-w-xl overflow-y-auto bg-[#fbf8f2] shadow-[-24px_0_60px_rgba(12,27,39,.18)]" onMouseDown={e=>e.stopPropagation()}><div className="sticky top-0 z-10 flex items-center justify-between border-b border-stone-200/80 bg-[#fbf8f2]/95 px-6 py-5"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-[#8b6d42]">{title}</p><button className="rounded-full border border-stone-300 bg-white px-3 py-1.5 text-xs" onClick={onClose}>Cerrar</button></div><div className="p-6 sm:p-8">{children}</div></aside></div>}
export function Avatar({name}:{readonly name:string}){return <span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e9dfcf] text-[10px] font-bold text-[#6f5633]">{name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span>}
export function PropertyMedia({variant=0,className="h-44"}:{readonly variant?:number;readonly className?:string}){return <div className={`nova-media ${className}`} data-variant={String(variant%3)}><span className="absolute bottom-3 right-4 text-[9px] font-bold uppercase tracking-[.24em] text-white/90">NOVA Selection</span></div>}
export function SectionTitle({eyebrow,title,aside}:{readonly eyebrow?:string;readonly title:string;readonly aside?:ReactNode}){return <div className="flex items-end justify-between gap-4"><div>{eyebrow&&<p className="text-[9px] font-bold uppercase tracking-[.24em] text-[#9a7b50]">{eyebrow}</p>}<h3 className="mt-1 font-serif text-xl font-semibold text-[#182f43]">{title}</h3></div>{aside}</div>}
