"use client";
import{DemoShell}from"@software-factory/demo-shell";
import{partxCategories,partxLocations,partxMetadata,partxMovements,partxProducts,partxStockLevels,partxThresholds,vehicleCompatibilities}from"@software-factory/mock-data/autoparts";
import{StockDemoProvider,type StockDemoScenario,type StockPresentationAdapter}from"@software-factory/stock-core";
import{autopartsVertical}from"@software-factory/verticals/autoparts";
import{usePathname}from"next/navigation";import type{ReactNode}from"react";import{PartxIcon}from"./partx-icon";
const names=["dashboard","parts","compatibility","movements","locations","alerts","suppliers","reports","settings"];
const scenario:StockDemoScenario={products:partxProducts,categories:partxCategories,locations:partxLocations,stockLevels:partxStockLevels,thresholds:partxThresholds,movements:partxMovements,demoTimestamp:"2026-09-08T14:00:00"};
const adapter:StockPresentationAdapter={searchText:(product)=>{const meta=partxMetadata[product.id];return `${meta?.brand??""} ${(meta?.compatibilityIds??[]).map(id=>{const vehicle=vehicleCompatibilities.find(item=>item.id===id);return `${vehicle?.make??""} ${vehicle?.model??""}`}).join(" ")}`}};
export function PartxShell({children}:{readonly children:ReactNode}){const path=usePathname();const nav=autopartsVertical.navigation.map((x,i)=>({...x,icon:<PartxIcon name={names[i]??"more"}/>}));return <StockDemoProvider scenario={scenario} adapter={adapter}><DemoShell brandMark="PX" businessName="PARTX Auto Parts" contextLabel="PARTX" currentPath={path} mobileNavigation={[{...nav[0]!,label:"Inicio"},nav[1]!,nav[2]!,nav[3]!]} mobileOverflowIcon={<PartxIcon name="more"/>} mobileOverflowNavigation={[nav[4]!,nav[5]!,nav[6]!,nav[7]!,nav[8]!]} navigation={nav} pageTitle={nav.find(x=>x.href===path)?.label??"Parts"} productLabel="Parts & Inventory" profileInitials="MR" profileLabel="Micaela · Catálogo" theme={{accent:"#28738a",accentSoft:"#e3f0f3",accentText:"#255f71",badgeBackground:"#dcebf0",badgeText:"#255f71",brandMarkColor:"#8ec8d6",background:"#f3f5f6",foreground:"#182329",navigationDot:"#65aec0",navigationIcon:"#8ec8d6",sidebar:"#20282d",surface:"#fff"}}>{children}</DemoShell></StockDemoProvider>}
