"use client";

import{motion}from"motion/react";
import{useCallback,useEffect,useId,useRef,useState,type ComponentPropsWithoutRef}from"react";

export interface AnimatedGridPatternProps extends ComponentPropsWithoutRef<"svg">{width?:number;height?:number;x?:number;y?:number;strokeDasharray?:number;numSquares?:number;maxOpacity?:number;duration?:number;repeatDelay?:number}
type Square={id:number;pos:[number,number];iteration:number};
type Dimensions={width:number;height:number};

export function AnimatedGridPattern({width=40,height=40,x=-1,y=-1,strokeDasharray=0,numSquares=50,className="",maxOpacity=.5,duration=4,repeatDelay=.5,...props}:AnimatedGridPatternProps){const id=useId();const containerRef=useRef<SVGSVGElement|null>(null);const dimensionsRef=useRef<Dimensions>({width:0,height:0});const[squares,setSquares]=useState<Square[]>([]);const getPos=useCallback(():[number,number]=>[Math.floor(Math.random()*dimensionsRef.current.width/width),Math.floor(Math.random()*dimensionsRef.current.height/height)],[height,width]);const generateSquares=useCallback((count:number)=>Array.from({length:count},(_,index)=>({id:index,pos:getPos(),iteration:0})),[getPos]);const updateSquarePosition=useCallback((squareId:number)=>{setSquares(current=>{const square=current[squareId];if(!square||square.id!==squareId)return current;const next=current.slice();next[squareId]={...square,pos:getPos(),iteration:square.iteration+1};return next})},[getPos]);useEffect(()=>{const element=containerRef.current;if(!element)return;const observer=new ResizeObserver(entries=>{for(const entry of entries){const next={width:entry.contentRect.width,height:entry.contentRect.height};const current=dimensionsRef.current;if(current.width===next.width&&current.height===next.height)continue;dimensionsRef.current=next;setSquares(generateSquares(numSquares))}});observer.observe(element);return()=>observer.disconnect()},[generateSquares,numSquares]);return <svg aria-hidden="true" className={`animated-grid-pattern ${className}`} ref={containerRef} {...props}><defs><pattern height={height} id={id} patternUnits="userSpaceOnUse" width={width} x={x} y={y}><path d={`M.5 ${height}V.5H${width}`} fill="none" strokeDasharray={strokeDasharray}/></pattern></defs><rect fill={`url(#${id})`} height="100%" width="100%"/><svg className="animated-grid-squares" x={x} y={y}>{squares.map(({pos:[squareX,squareY],id:squareId,iteration},index)=><motion.rect animate={{opacity:maxOpacity}} fill="currentColor" height={height-1} initial={{opacity:0}} key={`${squareId}-${iteration}`} onAnimationComplete={()=>updateSquarePosition(squareId)} strokeWidth="0" transition={{duration,repeat:1,delay:index*.1,repeatType:"reverse",repeatDelay}} width={width-1} x={squareX*width+1} y={squareY*height+1}/>)}</svg></svg>}
