"use client";
import { useEffect, useState } from "react";
const links = [["Programitas", "#programitas"], ["A medida", "#a-medida"], ["Casos reales", "#casos"], ["Precios", "#modelos"]] as const;
export function SiteHeader() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const [active, setActive] = useState("");
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 28); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { document.body.classList.toggle("menu-open", open); return () => document.body.classList.remove("menu-open"); }, [open]);
  useEffect(() => { const sections = links.map(([, href]) => document.querySelector(href)).filter(Boolean) as Element[]; const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (visible) setActive(`#${visible.target.id}`); }, { rootMargin: "-30% 0px -60%", threshold: [0, .2, .5] }); sections.forEach((section) => observer.observe(section)); return () => observer.disconnect(); }, []);
  return <header className={`site-header${scrolled ? " is-scrolled" : ""}`}><div className="shell header-inner"><a className="wordmark" href="#inicio" aria-label="Programita, inicio">PROGRAMITA<span>.</span></a><nav className="desktop-nav" aria-label="Navegación principal">{links.map(([label, href]) => <a aria-current={active === href ? "location" : undefined} className={active === href ? "is-active" : ""} href={href} key={href}>{label}</a>)}</nav><a className="header-cta" href="#programitas">Encontrá el tuyo <span aria-hidden>↘</span></a><button className="menu-toggle" type="button" aria-expanded={open} aria-label={open ? "Cerrar menú" : "Abrir menú"} onClick={() => setOpen((value) => !value)}><span /><span /></button></div><div className={`mobile-menu${open ? " is-open" : ""}`} aria-hidden={!open}><nav aria-label="Navegación móvil">{links.map(([label, href], index) => <a href={href} key={href} onClick={() => setOpen(false)}><small>0{index + 1}</small>{label}</a>)}<a href="#contacto" onClick={() => setOpen(false)}><small>05</small>Contacto</a></nav><p>Software para la gente.</p></div></header>;
}
