import type { Category,Location,LowStockThreshold,Product,StockLevel,StockMovement } from "@software-factory/stock-core";
export interface AutoPartMetadata{readonly partNumber:string;readonly manufacturer:string;readonly brand:string;readonly oemReferences?:readonly string[];readonly compatibilityIds:readonly string[];readonly demand:"high"|"medium"|"low";}
export interface VehicleCompatibility{readonly id:string;readonly make:string;readonly model:string;readonly yearFrom:number;readonly yearTo:number;readonly trim?:string;readonly engine?:string;}
export interface PartxSupplier{readonly id:string;readonly name:string;readonly brands:readonly string[];readonly productIds:readonly string[];readonly leadTimeDays:number;readonly lastReceipt:string;readonly status:"active"|"review";}
export const partxMetrics={parts:3842,low:74,out:12,movements:31,value:6850000} as const;
export const partxCategories:Category[]=[{id:"brakes",name:"Frenos"},{id:"engine",name:"Motor"},{id:"filters",name:"Filtros"},{id:"suspension",name:"Suspensión"},{id:"electric",name:"Eléctrico"},{id:"care",name:"Fluidos y cuidado"}];
export const partxLocations:Location[]=[{id:"main",name:"Depósito principal",code:"DEP"},{id:"zf",name:"Zona F · Frenos",code:"F",parentLocationId:"main"},{id:"f01",name:"Rack F-01",code:"F-01",parentLocationId:"zf"},{id:"f12",name:"Rack F-12",code:"F-12",parentLocationId:"zf"},{id:"zm",name:"Zona M · Motor",code:"M",parentLocationId:"main"},{id:"m01",name:"Rack M-01",code:"M-01",parentLocationId:"zm"},{id:"m03",name:"Rack M-03",code:"M-03",parentLocationId:"zm"},{id:"zs",name:"Zona S · Suspensión",code:"S-01",parentLocationId:"main"},{id:"counter",name:"Mostrador",code:"MOST",parentLocationId:"main"}];
export const vehicleCompatibilities:VehicleCompatibility[]=[{id:"bmw3",make:"BMW",model:"Serie 3",trim:"320i / 330i",yearFrom:2019,yearTo:2024,engine:"2.0T"},{id:"bmw4",make:"BMW",model:"Serie 4",trim:"420i",yearFrom:2020,yearTo:2024},{id:"golf",make:"Volkswagen",model:"Golf",yearFrom:2016,yearTo:2023},{id:"a3",make:"Audi",model:"A3",yearFrom:2016,yearTo:2023},{id:"leon",make:"Seat",model:"León",yearFrom:2017,yearTo:2023},{id:"hilux",make:"Toyota",model:"Hilux",yearFrom:2021,yearTo:2024},{id:"corolla",make:"Toyota",model:"Corolla",yearFrom:2018,yearTo:2023},{id:"ranger",make:"Ford",model:"Ranger",yearFrom:2020,yearTo:2024},{id:"focus",make:"Ford",model:"Focus",yearFrom:2017,yearTo:2022},{id:"amarok",make:"Volkswagen",model:"Amarok",yearFrom:2018,yearTo:2024}];
const rows=[
 ["P85020","Pastillas de freno delanteras","Brembo","brakes",["bmw3","bmw4"],"high",18500],["W71295","Filtro de aceite","Mann","filters",["golf","a3","leon"],"high",6800],["AF8155","Filtro de aire","Bosch","filters",["hilux"],"medium",9400],["DF3301","Discos de freno delanteros","Fremax","brakes",["bmw3"],"high",44500],["SP4420","Bujías iridium x4","NGK","engine",["corolla","focus"],"medium",23800],["AM9021","Amortiguador delantero","Monroe","suspension",["bmw3"],"high",69000],["CT7780","Correa distribución kit","Gates","engine",["golf","a3"],"medium",52200],["OS1142","Sensor de oxígeno","Bosch","electric",["corolla"],"low",33700],["HL7731","Lámpara H7 premium","Philips","electric",["golf","focus","ranger"],"high",8900],["BAT70X","Batería 70Ah","Willard","electric",["ranger","amarok"],"high",78500],["WB2216","Escobillas 22/16","Bosch","care",["corolla","golf"],"medium",13200],["BR6204","Rodamiento delantero","SKF","suspension",["hilux","ranger"],"medium",39700],["COOL5","Refrigerante orgánico 5L","Total","care",["hilux","ranger","amarok"],"medium",11600],["BP4422","Pastillas de freno traseras","TRW","brakes",["golf","a3","leon"],"medium",16900],["FF9020","Filtro de combustible","Mahle","filters",["amarok","ranger"],"high",14500],["SH1138","Amortiguador trasero","Sachs","suspension",["corolla"],"low",57400],["ALT884","Alternador 120A","Valeo","electric",["focus"],"medium",129000],["TB330","Tensor de correa","INA","engine",["golf","a3"],"medium",28400],["BF721","Líquido de frenos DOT4","Bosch","care",["bmw3","bmw4","golf"],"medium",7200],["CF110","Filtro de habitáculo","Mann","filters",["bmw3","bmw4"],"high",9800]
] as const;
export const partxProducts:Product[]=rows.map(([code,name,brand,categoryId,, ,unitCost],i)=>({id:`ap${i+1}`,sku:`PX-${code}`,name,categoryId,unit:"unidad",unitCost,metadata:{partNumber:code,manufacturer:brand,brand}}));
export const partxMetadata:Readonly<Record<string,AutoPartMetadata>>=Object.fromEntries(rows.map(([partNumber,,brand,,compatibilityIds,demand],i)=>[`ap${i+1}`,{partNumber,manufacturer:brand,brand,compatibilityIds,demand,oemReferences:i<3?[`DEMO-OEM-${100+i}`]:undefined}]));
const quantities=[7,0,4,11,23,0,6,9,28,3,16,8,20,14,2,7,1,12,25,5];const mins=[4,8,6,5,10,3,8,4,12,5,8,5,10,6,5,4,2,6,12,7];const locations=["f12","m03","m01","f01","m01","zs","m03","m01","counter","counter","counter","zs","m01","f01","m03","zs","m01","m03","counter","m03"];
export const partxStockLevels:StockLevel[]=partxProducts.flatMap((p,i)=>i===0?[{productId:p.id,locationId:"f12",quantity:5},{productId:p.id,locationId:"counter",quantity:2}]:[{productId:p.id,locationId:locations[i]??"m01",quantity:quantities[i]??0}]);
export const partxThresholds:LowStockThreshold[]=partxProducts.map((p,i)=>({productId:p.id,locationId:locations[i]??"m01",minimumQuantity:mins[i]??1}));
export const partxSuppliers:PartxSupplier[]=[{id:"ps1",name:"EuroParts Distribución",brands:["Brembo","Mann","Sachs"],productIds:["ap1","ap2","ap6","ap16","ap20"],leadTimeDays:3,lastReceipt:"06 sep 2026",status:"active"},{id:"ps2",name:"MotorLine Argentina",brands:["Bosch","NGK","Gates"],productIds:["ap3","ap5","ap7","ap8","ap9","ap11","ap19"],leadTimeDays:2,lastReceipt:"07 sep 2026",status:"active"},{id:"ps3",name:"Tracción Repuestos",brands:["Monroe","SKF","TRW"],productIds:["ap4","ap6","ap12","ap14"],leadTimeDays:5,lastReceipt:"01 sep 2026",status:"review"},{id:"ps4",name:"Ruta 8 Autopartes",brands:["Willard","Mahle","Valeo","INA"],productIds:["ap10","ap13","ap15","ap17","ap18"],leadTimeDays:4,lastReceipt:"04 sep 2026",status:"active"}];
export const partxMovements:StockMovement[]=[{id:"am1",productId:"ap1",type:"inbound",quantity:12,destinationLocationId:"f12",occurredAt:"2026-09-08T09:18:00",actorName:"Laura Vega",reference:"Recepción demo #RP-381"},{id:"am2",productId:"ap2",type:"outbound",quantity:2,sourceLocationId:"m03",occurredAt:"2026-09-08T09:47:00",actorName:"Nicolás Paz",reference:"Venta mostrador #VM-702"},{id:"am3",productId:"ap10",type:"transfer",quantity:4,sourceLocationId:"main",destinationLocationId:"counter",occurredAt:"2026-09-08T10:22:00",actorName:"Laura Vega",reference:"Reposición mostrador #TR-118"},{id:"am4",productId:"ap6",type:"outbound",quantity:1,sourceLocationId:"zs",occurredAt:"2026-09-08T10:51:00",actorName:"Nicolás Paz",reference:"Reserva demo #RS-204"},{id:"am5",productId:"ap3",type:"adjustment",quantity:1,adjustmentDirection:"decrease",sourceLocationId:"m01",occurredAt:"2026-09-08T11:14:00",actorName:"Micaela Ruiz",reference:"Control visual #AJ-051"},{id:"am6",productId:"ap9",type:"inbound",quantity:20,destinationLocationId:"counter",occurredAt:"2026-09-08T12:03:00",actorName:"Laura Vega",reference:"Recepción demo #RP-384"}];
