import type{Activity,Contact,Opportunity,Pipeline,Task}from"@software-factory/crm-core";
export interface AgentProfile{readonly id:string;readonly name:string;readonly initials:string;readonly role:string}
export interface Property{readonly id:string;readonly title:string;readonly type:string;readonly address:string;readonly zone:string;readonly price:number;readonly bedrooms:number;readonly area:number;readonly status:"Disponible"|"Reservada"|"Vendida";readonly agentId:string}
export interface Visit{readonly id:string;readonly propertyId:string;readonly contactId:string;readonly agentId:string;readonly startsAt:string;readonly status:"Confirmada"|"Pendiente"|"Realizada"}
export const agents:AgentProfile[]=[{id:"a1",name:"Valentina Paz",initials:"VP",role:"Asesora senior"},{id:"a2",name:"Tomás Riva",initials:"TR",role:"Asesor comercial"},{id:"a3",name:"Lucía Ferrer",initials:"LF",role:"Team leader"}];
const names=["Martín Suárez","Carolina Méndez","Federico Luna","Sofía Aguirre","Diego Romero","Paula Costa","Ignacio Vidal","Julieta Torres","Andrés Molina","Camila Ríos","Nicolás Vega","Florencia Ruiz","Emilia Castro","Gonzalo Silva"];
export const contacts:Contact[]=names.map((name,i)=>({id:`c${i+1}`,name,phone:`+54 11 5555 ${String(1100+i)}`,email:`${name.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(" ",".")}@mail.com`,metadata:{source:["Portal","Referido","Instagram","Web"][i%4],budget:180000+i*35000}}));
export const properties:Property[]=[
 {id:"p1",title:"Casa Jardines del Sur",type:"Casa",address:"Los Aromos 184",zone:"Nordelta",price:420000,bedrooms:4,area:286,status:"Disponible",agentId:"a1"},{id:"p2",title:"Departamento Río",type:"Departamento",address:"Av. del Libertador 6210",zone:"Belgrano",price:265000,bedrooms:3,area:118,status:"Disponible",agentId:"a2"},{id:"p3",title:"Loft Distrito Arte",type:"Loft",address:"Honduras 4821",zone:"Palermo",price:198000,bedrooms:1,area:74,status:"Reservada",agentId:"a1"},{id:"p4",title:"Casa Bosque Central",type:"Casa",address:"Acacias 91",zone:"San Isidro",price:610000,bedrooms:5,area:355,status:"Disponible",agentId:"a3"},{id:"p5",title:"Piso Parque",type:"Departamento",address:"Cabello 3340",zone:"Palermo",price:345000,bedrooms:3,area:142,status:"Disponible",agentId:"a2"},{id:"p6",title:"Dúplex Laguna",type:"Dúplex",address:"Los Sauces 442",zone:"Tigre",price:310000,bedrooms:3,area:164,status:"Vendida",agentId:"a1"},{id:"p7",title:"Estudio Central",type:"Departamento",address:"Tucumán 844",zone:"Microcentro",price:122000,bedrooms:1,area:48,status:"Disponible",agentId:"a3"},{id:"p8",title:"Casa Patio Norte",type:"Casa",address:"Alvear 1290",zone:"Martínez",price:475000,bedrooms:4,area:248,status:"Disponible",agentId:"a2"},{id:"p9",title:"Penthouse Horizonte",type:"Penthouse",address:"Juana Manso 1555",zone:"Puerto Madero",price:890000,bedrooms:4,area:302,status:"Reservada",agentId:"a3"}];
export const pipeline:Pipeline={id:"sales",name:"Pipeline comercial",stages:["Nuevo lead","Contactado","Interesado","Visita agendada","Negociación","Reserva","Cerrado"].map((label,order)=>({id:`s${order+1}`,label,order}))};
export const opportunities:Opportunity[]=Array.from({length:12},(_,i)=>({id:`o${i+1}`,contactId:`c${i+1}`,pipelineId:"sales",stageId:`s${Math.min(7,(i%7)+1)}`,title:properties[i%9]!.title,value:properties[i%9]!.price,ownerId:`a${(i%3)+1}`,status:i===6?"won":"open",createdAt:`2026-08-${String(18+i).padStart(2,"0")}`,metadata:{propertyId:`p${(i%9)+1}`,source:["Portal","Referido","Web"][i%3]}}));
export const tasks:Task[]=Array.from({length:10},(_,i)=>({id:`t${i+1}`,opportunityId:`o${(i%10)+1}`,contactId:`c${(i%10)+1}`,title:["Llamar para validar interés","Enviar ficha y planos","Confirmar disponibilidad","Coordinar próxima visita"][i%4]!,dueAt:`2026-09-${String(8+Math.floor(i/3)).padStart(2,"0")}T${String(10+i%6).padStart(2,"0")}:00:00`,ownerId:`a${(i%3)+1}`,status:i===2?"completed":"open"}));
export const activities:Activity[]=Array.from({length:10},(_,i)=>({id:`ac${i+1}`,contactId:`c${(i%10)+1}`,opportunityId:`o${(i%10)+1}`,type:["call","message","meeting","note"][i%4] as Activity["type"],occurredAt:`2026-09-${String(7-Math.floor(i/4)).padStart(2,"0")}T${String(9+i%7).padStart(2,"0")}:30:00`,summary:["Conversación inicial","Ficha enviada","Interés confirmado","Preferencias registradas"][i%4]!,ownerId:`a${(i%3)+1}`}));
export const visits:Visit[]=Array.from({length:7},(_,i)=>({id:`v${i+1}`,propertyId:`p${(i%7)+1}`,contactId:`c${(i%7)+1}`,agentId:`a${(i%3)+1}`,startsAt:`2026-09-${String(8+Math.floor(i/4)).padStart(2,"0")}T${String(10+(i%4)*2).padStart(2,"0")}:00:00`,status:i===5?"Realizada":i===6?"Pendiente":"Confirmada"}));
export const novaMetrics={activeLeads:48,opportunities:27,weeklyVisits:12,pipelineValue:1420000,conversion:18}as const;
