import { StatusBadge } from "@software-factory/ui";
import { tallerClients, tallerServices, tallerVehicles, tallerWorkOrders } from "@software-factory/mock-data/taller";
import { TallerPageHeader, TallerPanel, formatTallerCurrency } from "../_components/taller-primitives";

export default function TallerClientsPage() {
  return <><TallerPageHeader description="Relación comercial construida alrededor de sus vehículos y órdenes recientes." eyebrow="Cartera del taller" title="Clientes y sus vehículos" />
    <div className="mb-5"><input aria-label="Buscar cliente" className="w-full max-w-md rounded-xl border border-stone-200 bg-white px-4 py-3 text-sm" placeholder="Buscar por nombre, teléfono o patente..." /></div>
    <div className="grid gap-4 xl:grid-cols-2">{tallerClients.map((client) => { const vehicles=tallerVehicles.filter(item=>item.clientId===client.id); const orders=tallerWorkOrders.filter(item=>item.clientId===client.id); return <details className="group" key={client.id}><summary className="list-none cursor-pointer [&::-webkit-details-marker]:hidden"><TallerPanel className="p-5 transition group-open:rounded-b-none group-open:border-amber-300"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#252a26] text-xs font-black text-amber-200">{client.name.split(" ").map(word=>word[0]).join("")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-black">{client.name}</h3><span className="text-xs font-bold text-amber-700">Ver ficha +</span></div><p className="mt-1 text-xs text-stone-500">{client.phone}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-stone-100 p-2"><strong className="block">{vehicles.length}</strong><span className="text-[9px] text-stone-400">vehículos</span></div><div className="rounded-lg bg-stone-100 p-2"><strong className="block">{client.visits}</strong><span className="text-[9px] text-stone-400">visitas</span></div><div className="rounded-lg bg-stone-100 p-2"><strong className="block text-xs">{formatTallerCurrency(client.totalSpend)}</strong><span className="text-[9px] text-stone-400">acumulado</span></div></div></div></div></TallerPanel></summary><div className="rounded-b-2xl border border-t-0 border-amber-300 bg-[#fffefa] p-5"><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-stone-400">Vehículos asociados</p>{vehicles.map(vehicle=><div className="mt-3 rounded-xl border border-stone-200 p-3" key={vehicle.id}><p className="text-sm font-bold">{vehicle.model} {vehicle.year}</p><p className="mt-1 font-mono text-xs text-amber-700">{vehicle.plate}</p></div>)}</div><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-stone-400">Actividad</p><p className="mt-3 text-sm text-stone-600">Última visita: <strong>{client.lastVisit}</strong></p><p className="mt-2 text-sm text-stone-600">Próximo turno: <strong>{client.nextBooking ?? "Sin turno"}</strong></p>{orders.slice(0,2).map(order=><div className="mt-3 flex items-center justify-between rounded-xl bg-stone-100 p-3" key={order.id}><div><p className="font-mono text-xs font-bold">OT #{order.number}</p><p className="text-[10px] text-stone-500">{order.serviceIds.map(id=>tallerServices.find(service=>service.id===id)?.name).join(" · ")}</p></div><StatusBadge tone="warning">{formatTallerCurrency(order.estimate)}</StatusBadge></div>)}</div></div></div></details> })}</div>
  </>;
}
