import { ProgressBar, StatusBadge } from "@software-factory/ui";
import { tallerMechanics } from "@software-factory/mock-data/taller";
import { TallerPageHeader, TallerPanel, formatTallerCurrency } from "../_components/taller-primitives";

export default function TallerMechanicsPage() {
  return <><TallerPageHeader description="Capacidad, especialidad y carga de cada integrante del equipo técnico." eyebrow="Equipo técnico" title="Mecánicos" />
    <div className="grid gap-5 xl:grid-cols-3">{tallerMechanics.map((mechanic, index) => <TallerPanel className="overflow-hidden" key={mechanic.id}><div className="h-2 bg-gradient-to-r from-[#303632] to-[#d97706]"/><div className="p-5"><div className="flex items-start justify-between"><span className="grid size-14 place-items-center rounded-xl bg-[#272b28] text-sm font-black text-amber-200">{mechanic.avatar}</span><StatusBadge tone={index === 0 ? "warning" : "success"}>{index === 0 ? "Alta carga" : "Disponible"}</StatusBadge></div><h3 className="mt-5 text-2xl font-black tracking-tight">{mechanic.name}</h3><p className="mt-1 text-sm font-medium text-amber-700">{mechanic.role}</p><div className="mt-6 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-stone-100 p-3"><strong className="block text-xl">{mechanic.weeklyJobs}</strong><span className="text-[9px] text-stone-500">trabajos</span></div><div className="rounded-xl bg-stone-100 p-3"><strong className="block text-xl">{mechanic.vehiclesAssigned}</strong><span className="text-[9px] text-stone-500">asignados</span></div><div className="rounded-xl bg-stone-100 p-3"><strong className="block text-sm">{formatTallerCurrency(mechanic.revenue)}</strong><span className="text-[9px] text-stone-500">facturación</span></div></div><ProgressBar className="mt-6" label="Ocupación" value={mechanic.occupation} /><div className="mt-5 flex flex-wrap gap-2">{mechanic.specialties.map((item) => <span className="rounded-full border border-stone-200 px-2.5 py-1 text-[10px] font-bold text-stone-500" key={item}>{item}</span>)}</div></div></TallerPanel>)}</div>
  </>;
}
