import { nexusAppointments, nexusDashboard, nexusPatients, nexusProfessionals, nexusServices } from "@software-factory/mock-data/consultorio";
import { ProgressBar, StatusBadge } from "@software-factory/ui";
import { NexusIcon } from "../_components/nexus-icon";
import { NexusPageHeader, NexusPanel, NexusSectionTitle } from "../_components/nexus-primitives";

const statusLabels = { cancelled: "Cancelado", completed: "Finalizado", confirmed: "Confirmado", in_progress: "En consulta", pending: "En espera" } as const;

export default function ConsultorioDashboardPage() {
  const next = nexusAppointments.filter((item) => ["confirmed", "pending", "in_progress"].includes(item.status)).slice(0, 5);
  const maxDemand = Math.max(...nexusDashboard.timeDemand.map((item) => item.value));
  return <>
    <NexusPageHeader action={<a className="rounded-2xl bg-[#263836] px-5 py-3 text-sm font-semibold text-white" href="/consultorio/agenda">Abrir agenda →</a>} description="Recepción, agenda y seguimiento administrativo en una vista tranquila y clara." eyebrow="Martes, 8 de septiembre · Jornada administrativa" title="Buenos días, Ana" />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{nexusDashboard.kpis.map((item, index) => <NexusPanel className="p-5" key={item.label}><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-[#71817e]">{item.label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-[#263432]">{item.value}</p></div><span className="grid size-10 place-items-center rounded-2xl bg-[#e8f2ef] text-[#347b78]"><NexusIcon name={index === 0 ? "agenda" : index === 3 ? "dashboard" : "consultations"}/></span></div><p className="mt-4 text-xs text-[#82908d]">{item.detail}</p></NexusPanel>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.75fr]">
      <NexusPanel className="overflow-hidden"><div className="border-b border-[#e3e9e6] p-5 sm:p-6"><NexusSectionTitle detail="Pacientes que requieren atención de recepción" title="Próximas consultas" /></div><div className="divide-y divide-[#e5ebe8]">{next.map((booking) => { const patient=nexusPatients.find((item)=>item.id===booking.customerId)!; const professional=nexusProfessionals.find((item)=>item.id===booking.resourceId)!; const service=nexusServices.find((item)=>item.id===booking.serviceId)!; return <a className="grid gap-3 px-5 py-4 transition hover:bg-[#f7faf8] sm:grid-cols-[4rem_1fr_auto] sm:items-center sm:px-6" href="/consultorio/consultas" key={booking.id}><p className="text-lg font-semibold text-[#2c5552]">{booking.start.slice(11,16)}</p><div><p className="text-sm font-semibold text-[#263432]">{patient.name}</p><p className="mt-1 text-xs text-[#71817e]">{service.name} · {professional.name}</p></div><StatusBadge tone={booking.status === "in_progress" ? "info" : booking.status === "confirmed" ? "success" : "warning"}>{statusLabels[booking.status]}</StatusBadge></a>; })}</div></NexusPanel>
      <NexusPanel className="p-5 sm:p-6"><NexusSectionTitle detail="Resumen visual del escenario" title="Estado de la jornada"/><div className="mt-6 grid grid-cols-2 gap-3">{[{label:"Atendidos",value:9,tone:"bg-[#dcebe5] text-[#285f59]"},{label:"Pendientes",value:6,tone:"bg-[#f4eedc] text-[#866d2e]"},{label:"Confirmados",value:2,tone:"bg-[#e5edf2] text-[#476675]"},{label:"Cancelado",value:1,tone:"bg-stone-100 text-stone-500"}].map(item=><div className={`rounded-2xl p-4 ${item.tone}`} key={item.label}><p className="text-3xl font-semibold">{item.value}</p><p className="mt-1 text-xs">{item.label}</p></div>)}</div></NexusPanel>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-3"><NexusPanel className="p-5 sm:p-6"><NexusSectionTitle detail="Porcentaje simulado de agenda ocupada" title="Ocupación semanal"/><div className="mt-6 space-y-4">{nexusDashboard.weeklyOccupation.map(item=><ProgressBar key={item.day} label={item.day} value={item.value}/>)}</div></NexusPanel><NexusPanel className="p-5 sm:p-6"><NexusSectionTitle detail="Distribución administrativa" title="Consultas por tipo"/><div className="mt-6 space-y-5">{nexusDashboard.typeDemand.map(item=><ProgressBar key={item.name} label={item.name} value={item.value}/>)}</div></NexusPanel><NexusPanel className="p-5 sm:p-6"><NexusSectionTitle detail="Preferencias de horario observadas" title="Demanda por franja"/><div className="mt-8 flex h-44 items-end gap-4">{nexusDashboard.timeDemand.map(item=><div className="flex flex-1 flex-col items-center gap-2" key={item.label}><span className="text-[10px] font-semibold text-[#71817e]">{item.value}%</span><div className="w-full rounded-t-xl bg-[#79a99c]" style={{height:`${item.value/maxDemand*120}px`}}/><span className="text-[10px] text-[#82908d]">{item.label}</span></div>)}</div></NexusPanel></div>
  </>;
}
