import { ProgressBar } from "@software-factory/ui";
import { tallerMechanics, tallerReports, tallerServices, tallerWorkOrders } from "@software-factory/mock-data/taller";
import { TallerIcon } from "../_components/taller-icon";
import { TallerPageHeader, TallerPanel, TallerSectionTitle, formatTallerCurrency } from "../_components/taller-primitives";

export default function TallerReportsPage() {
  const cards=[{label:"Facturación mensual",value:formatTallerCurrency(tallerReports.monthlyRevenue),detail:"+8,4% vs. agosto"},{label:"Trabajos realizados",value:String(tallerReports.completedJobs),detail:"12 durante esta semana"},{label:"Ticket promedio",value:formatTallerCurrency(tallerReports.averageTicket),detail:"Sobre órdenes cerradas"},{label:"Vehículos recurrentes",value:`${tallerReports.recurringVehicles}%`,detail:"Regresaron en los últimos 6 meses"}];
  return <><TallerPageHeader description="Indicadores comerciales para decidir con información operativa clara." eyebrow="Resumen gerencial · Septiembre 2026" title="Rendimiento del taller" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card=><TallerPanel className="p-5" key={card.label}><div className="flex justify-between"><p className="text-xs font-bold uppercase tracking-[.1em] text-stone-500">{card.label}</p><TallerIcon className="size-5 text-amber-700" name="chart"/></div><p className="mt-4 text-3xl font-black tracking-tight">{card.value}</p><p className="mt-3 text-xs text-stone-500">{card.detail}</p></TallerPanel>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><TallerPanel className="p-5 sm:p-6"><TallerSectionTitle detail="Participación estimada del mes" title="Servicios más vendidos"/><div className="mt-6 space-y-5">{tallerServices.slice(0,5).map((service,index)=><ProgressBar key={service.id} label={service.name} value={[84,73,68,55,49][index] ?? 0}/>)}</div></TallerPanel><TallerPanel className="p-5 sm:p-6"><TallerSectionTitle detail="Distribución de las órdenes del escenario" title="Órdenes por estado"/><div className="mt-6 grid grid-cols-2 gap-3">{[["Recibidas","received"],["Diagnóstico","diagnosis"],["En trabajo","in_progress"],["Esperando repuesto","waiting_parts"],["Listas","ready"]].map(([label,status])=><div className="rounded-xl bg-stone-100 p-4" key={status}><p className="text-3xl font-black">{tallerWorkOrders.filter(order=>order.status===status).length}</p><p className="mt-1 text-xs text-stone-500">{label}</p></div>)}</div></TallerPanel></div><TallerPanel className="mt-5 p-5 sm:p-6"><TallerSectionTitle detail="Métricas visuales no calculadas en tiempo real" title="Desempeño por mecánico"/><div className="mt-6 grid gap-4 md:grid-cols-3">{tallerMechanics.map(mechanic=><div className="rounded-xl border border-stone-200 p-4" key={mechanic.id}><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#252a26] text-[10px] font-black text-amber-200">{mechanic.avatar}</span><div><p className="text-sm font-bold">{mechanic.name}</p><p className="text-[10px] text-stone-400">{mechanic.role}</p></div></div><ProgressBar className="mt-5" label="Ocupación" value={mechanic.occupation}/><p className="mt-4 text-sm font-black">{formatTallerCurrency(mechanic.revenue)}</p></div>)}</div></TallerPanel></>;
}
