"use client";

import { nexusAppointments, nexusConsultations, nexusPatients, nexusProfessionals, nexusServices, type Consultation, type ConsultationStatus } from "@software-factory/mock-data/consultorio";
import { StatusBadge, type StatusTone } from "@software-factory/ui";
import { useEffect, useState } from "react";
import { NexusPanel, formatNexusCurrency } from "../_components/nexus-primitives";

const statusMap:Record<ConsultationStatus,{label:string;tone:StatusTone}>={confirmed:{label:"Confirmada",tone:"success"},waiting:{label:"En espera",tone:"warning"},in_session:{label:"En consulta",tone:"info"},completed:{label:"Finalizada",tone:"neutral"},cancelled:{label:"Cancelada",tone:"danger"}};

function ConsultationDetail({consultation,onClose}:{readonly consultation:Consultation;readonly onClose:()=>void}){
  useEffect(()=>{const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[onClose]);
  const booking=nexusAppointments.find(item=>item.id===consultation.bookingId)!;const patient=nexusPatients.find(item=>item.id===booking.customerId)!;const professional=nexusProfessionals.find(item=>item.id===booking.resourceId)!;const service=nexusServices.find(item=>item.id===booking.serviceId)!;
  const fields=[["Paciente",patient.name],["Profesional",professional.name],["Servicio",service.name],["Fecha","8 de septiembre de 2026"],["Horario",`${booking.start.slice(11,16)}—${booking.end.slice(11,16)}`],["Estado",statusMap[consultation.status].label],["Precio",formatNexusCurrency(service.price)]];
  return <div aria-labelledby="consultation-title" aria-modal="true" className="fixed inset-0 z-50 bg-[#1f302e]/40 backdrop-blur-[2px]" role="dialog"><button aria-label="Cerrar detalle" className="absolute inset-0 size-full" onClick={onClose} type="button"/><aside className="absolute inset-y-0 right-0 w-full max-w-lg overflow-y-auto bg-[#fffefb] p-5 shadow-2xl sm:p-7"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#347b78]">Consulta administrativa · Demo</p><h2 className="mt-2 text-3xl font-semibold" id="consultation-title">{patient.name}</h2><p className="mt-1 text-sm text-[#71817e]">{service.name}</p></div><button aria-label="Cerrar" autoFocus className="grid size-9 place-items-center rounded-full bg-[#edf2ef]" onClick={onClose} type="button">×</button></div><div className="mt-7 flex items-center justify-between rounded-2xl bg-[#e8f2ef] p-4"><div><p className="text-xs text-[#60716e]">{booking.start.slice(11,16)} · {professional.name}</p><p className="mt-1 text-sm font-semibold text-[#263432]">{consultation.nextAction}</p></div><StatusBadge tone={statusMap[consultation.status].tone}>{statusMap[consultation.status].label}</StatusBadge></div><dl className="mt-6 divide-y divide-[#e5ebe8] border-y border-[#e5ebe8]">{fields.map(([label,value])=><div className="flex justify-between gap-4 py-3.5" key={label}><dt className="text-xs font-semibold text-[#82908d]">{label}</dt><dd className="text-right text-sm font-medium text-[#435c59]">{value}</dd></div>)}</dl><div className="mt-6 rounded-2xl border border-[#c9ddd6] bg-[#f1f7f4] p-4"><p className="text-xs font-semibold text-[#347b78]">Nota administrativa</p><p className="mt-2 text-sm leading-6 text-[#60716e]">{consultation.administrativeNote}</p></div><button className="mt-8 w-full rounded-2xl bg-[#263836] px-4 py-3 text-sm font-semibold text-white" onClick={onClose} type="button">Actualizar estado · Simulado</button><p className="mt-3 text-center text-[10px] text-[#8b9895]">Sin información clínica · No se guardan cambios</p></aside></div>
}

export function ConsultationsExperience(){const[selected,setSelected]=useState<Consultation>();return <><NexusPanel className="mb-5 p-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{(["completed","waiting","in_session","confirmed","cancelled"]as const).map(status=><div className="rounded-2xl bg-[#f3f6f3] p-3" key={status}><p className="text-2xl font-semibold text-[#263432]">{nexusConsultations.filter(item=>item.status===status).length}</p><p className="mt-1 text-[10px] text-[#71817e]">{statusMap[status].label}</p></div>)}</div></NexusPanel><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{["Todas","En espera","En consulta","Confirmadas","Finalizadas"].map((item,index)=><button className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${index===0?"bg-[#263836] text-white":"border border-[#dbe3df] bg-white text-[#60716e]"}`} key={item} type="button">{item}</button>)}</div><NexusPanel className="overflow-hidden"><div className="hidden grid-cols-[.55fr_1.1fr_1.1fr_1fr_1fr] gap-4 border-b border-[#e5ebe8] bg-[#f6f8f5] px-5 py-3 text-[10px] font-semibold uppercase tracking-[.12em] text-[#82908d] md:grid"><span>Hora</span><span>Paciente</span><span>Consulta</span><span>Profesional</span><span>Recepción</span></div><div className="divide-y divide-[#e5ebe8]">{nexusConsultations.map(consultation=>{const booking=nexusAppointments.find(item=>item.id===consultation.bookingId)!;const patient=nexusPatients.find(item=>item.id===booking.customerId)!;const professional=nexusProfessionals.find(item=>item.id===booking.resourceId)!;const service=nexusServices.find(item=>item.id===booking.serviceId)!;return <button className="grid w-full gap-3 p-5 text-left transition hover:bg-[#f7faf8] md:grid-cols-[.55fr_1.1fr_1.1fr_1fr_1fr] md:items-center" key={consultation.id} onClick={()=>setSelected(consultation)} type="button"><div><p className="text-lg font-semibold text-[#2c5552]">{booking.start.slice(11,16)}</p><p className="text-[10px] text-[#82908d]">{service.durationMinutes} min</p></div><div><p className="text-sm font-semibold text-[#263432]">{patient.name}</p><p className="mt-1 text-[10px] text-[#82908d]">{patient.phone}</p></div><p className="text-xs text-[#526663]">{service.name}</p><p className="text-xs font-medium text-[#526663]">{professional.name}</p><div><StatusBadge tone={statusMap[consultation.status].tone}>{statusMap[consultation.status].label}</StatusBadge><p className="mt-2 text-[10px] text-[#82908d]">{consultation.nextAction}</p></div></button>})}</div></NexusPanel>{selected?<ConsultationDetail consultation={selected} onClose={()=>setSelected(undefined)}/>:null}</>}
